= university-bachelor-semester-project-3.contributing(7)
:commitizen: link:http://commitizen.github.io/cz-cli
:github-flow: link:http://scottchacon.com/2011/08/31/github-flow.html
:repository-blob: link:https://github.com/trueNAHO/university-bachelor-semester-project-3/blob/master
:toc:

:university-bachelor-semester-project-3-1: {repository-blob}/README.adoc
:university-bachelor-semester-project-3-code-of-conduct-7: {repository-blob}/docs/code_of_conduct.adoc

== Name

university-bachelor-semester-project-3.contributing - Contribution Guidelines

[[what-we-want]]
== What We Want

We welcome any contributions that help improve this project. Here are some
examples of the kinds of contributions we are looking for:

* Bug reports and feature requests
* Code improvements and bug fixes
* Design and performance improvements
* Documentation improvements

If you are uncertain about whether your contribution aligns with the scope of
this project, please review <<what-we-do-not-want, what we do not want>>. Feel
free to reach out to the maintainers, if you have any questions.

[[what-we-do-not-want]]
== What We Do Not Want

While we appreciate all contributions that help improve this project, some may
not align with our vision, require further discussion, or may be better suited
for a fork. Here are some examples that may fall into this category:

* Plagiarism
* Features exceeding final project deadline
* Security risks
* Performance overheads

If you are uncertain about whether your contribution aligns with the scope of
this project, please review <<what-we-want, what we want>>. Feel free to reach
out to the maintainers, if you have any questions.

== Contribution Guidelines

=== Contribution Process

Adhere to the {github-flow}[GitHub Flow].

=== Commit Messages

Follow {commitizen}[Commitizen]'s commit standards.

== See Also

{university-bachelor-semester-project-3-1}[university-bachelor-semester-project-3(1)],
{university-bachelor-semester-project-3-code-of-conduct-7}[university-bachelor-semester-project-3.code-of-conduct(7)],
